FROM golang:1.17 as builder

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

FROM golang:1.17-alpine 

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app .

RUN go build -v -o /usr/local/bin/app ./...


CMD ["app"]